/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.consultas;

import Reportes.rentasDataSource;
import com.capturas.*;
import java.awt.Color;

import com.login.biblio_funciones;
import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Elias
 */
public class Consultas extends javax.swing.JInternalFrame {
    
    /*
     * Creates new form c_Rentas
     */
        public static JPanel rentas_por_periodo = new JPanel();
        public static JPanel compras_por_periodo = new JPanel();
        public static JPanel localizar_libro = new JPanel();




    public Consultas() {
        initComponents();
        //tamaño de el internal frame maximo
        this.setSize(1366, 768);
        //tamaño de el internal frame minimo
        this.setMinimumSize(new java.awt.Dimension(1000, 600));
        
        //llenar al panel  elementos para seleccionar fecha final e inicial
        rentas_por_periodo.add(new JLabel("Fecha Inicial:"));
        rentas_por_periodo.add(new JDateChooser());
        rentas_por_periodo.add(new JLabel("Fecha Final:"));
        rentas_por_periodo.add(new JDateChooser());

        //llenar al panel 2 elementos para seleccionar fecha final e inicial
        compras_por_periodo.add(new JLabel("Fecha Inicial:"));
        compras_por_periodo.add(new JDateChooser());
        compras_por_periodo.add(new JLabel("Fecha Final:"));
        compras_por_periodo.add(new JDateChooser());
        
        //llenar al panel elementos para seleccionar por que parametro se va a buscar
        localizar_libro.add(new JLabel("Buscar por:"));
        localizar_libro.add(new JComboBox(new String[]{"ISBN", "Titulo", "Autor", "Editorial", "Genero"}));
        localizar_libro.add(new JLabel("Ingrese el valor:"));
        localizar_libro.add(new JTextField());
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        background.setBackground(new java.awt.Color(0, 102, 153));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        button1.setLabel("Generar Reporte");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        background.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 70));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONSULTAS");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione una consulta:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventas/Rentas en un periodo.", "Compras en un periodo.", "Localizar Libro." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Parametros:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        //Si presiono esc mostrar un dialog si presiona si se sale 
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            biblio_funciones.mensaje("Desea Salir?", "SALIR", 2);
        }
    }//GEN-LAST:event_formKeyPressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
      
    }//GEN-LAST:event_button1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //Cuando se seleccione una opcion del combobox se mostrara el panel correspondiente con los parametros necesarios
        switch(jComboBox1.getSelectedIndex()){
            case 0 -> {
                //Ventas y Rentas en un periodo
                //Pedir fecha inicial y final
                jPanel2.removeAll();
                jPanel2.repaint();
                jPanel2.revalidate();
                jPanel2.add(rentas_por_periodo);
                jPanel2.repaint();
                jPanel2.revalidate();
                }
            case 1 -> {
                //Compras a proveedores en un periodo
                //Pedir fecha inicial y final
                jPanel2.removeAll();
                jPanel2.repaint();
                jPanel2.revalidate();
                jPanel2.add(compras_por_periodo);
                jPanel2.repaint();
                jPanel2.revalidate();
                }
            case 2 -> {
                //Localizar libro por nombre
                //Pedir nombre del libro
                jPanel2.removeAll();
                jPanel2.repaint();
                jPanel2.revalidate();
                jPanel2.add(localizar_libro);
                jPanel2.repaint();
                jPanel2.revalidate();
                }
            default -> biblio_funciones.mensaje("Opcion no valida", "ERROR", 2);
        }

        //Cargar para el reporte de ventas y rentas en un periodo 
        if(jComboBox1.getSelectedIndex()==0){
            //Sacar las 2 fechas de los jdatechooser de rentas_por_periodo
            //String fecha_inicial = rentas_por_periodo.jDateChooser1.getDate().toString();
            // String fecha_final = rentas_por_periodo.jDateChooser2.getDate().toString();
            //Cargar el reporte con las fechas
            // cargarReporte(fecha_inicial+","+fecha_final);

        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    public void cargarReporte(String parametro){

       try {
            JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/Ventas1.jasper"));
            JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, rentasDataSource.getDataSource());
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setTitle("Reporte de ventas");
            jasperViewer.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            jasperViewer.setVisible(true);


       } catch (JRException e) {
           e.getMessage();
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private java.awt.Button button1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
