/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import com.abcs.*;
import com.capturas.*;
import com.consultas.c_Rentas;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
/**
 * @author Elias
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //Sacar la resolucion de la pantalla y poner el frame en el centro
        //que el maximo de la longitud y altura sea la resolucion de la pantalla
        this.setSize(getMaximumSize());
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        Abcs = new javax.swing.JMenu();
        Clientes = new javax.swing.JMenuItem();
        Proveedores = new javax.swing.JMenuItem();
        Libros = new javax.swing.JMenuItem();
        Autores = new javax.swing.JMenuItem();
        Tarjetas = new javax.swing.JMenuItem();
        Capturas = new javax.swing.JMenu();
        Ventas = new javax.swing.JMenuItem();
        Compras = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        Consulta1 = new javax.swing.JMenuItem();
        Consulta2 = new javax.swing.JMenuItem();
        Consulta3 = new javax.swing.JMenuItem();
        Limpiar = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(getMaximumSize());
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/logo_con_fondo-removebg-preview.png"))); // NOI18N
        jLabel10.setToolTipText("");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(621, 621, 621)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1304, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1431, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        Inicio.setText("Inicio");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Inicio.add(Salir);

        jMenuBar1.add(Inicio);

        Abcs.setText("Abcs");

        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        Abcs.add(Clientes);

        Proveedores.setText("Proveedores");
        Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresActionPerformed(evt);
            }
        });
        Abcs.add(Proveedores);

        Libros.setText("Libros");
        Libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrosActionPerformed(evt);
            }
        });
        Abcs.add(Libros);

        Autores.setText("Autores");
        Autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoresActionPerformed(evt);
            }
        });
        Abcs.add(Autores);

        Tarjetas.setText("Tarjetas");
        Tarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetasActionPerformed(evt);
            }
        });
        Abcs.add(Tarjetas);

        jMenuBar1.add(Abcs);

        Capturas.setText("Capturas");

        Ventas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        Ventas.setText("Ventas");
        Ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentasMouseClicked(evt);
            }
        });
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });
        Capturas.add(Ventas);

        Compras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        Compras.setText("Compras");
        Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprasActionPerformed(evt);
            }
        });
        Capturas.add(Compras);

        jMenuBar1.add(Capturas);

        Consultas.setText("Consultas");

        Consulta1.setText("Rentas");
        Consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta1ActionPerformed(evt);
            }
        });
        Consultas.add(Consulta1);

        Consulta2.setText("Compras");
        Consultas.add(Consulta2);

        Consulta3.setText("Localizacion Libros");
        Consultas.add(Consulta3);

        jMenuBar1.add(Consultas);

        Limpiar.setText("Limpiar todo");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jMenuBar1.add(Limpiar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29373, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29075, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasMouseClicked
   
    }//GEN-LAST:event_VentasMouseClicked

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
        //Abrrir el formulario de ventas
     
        Ventas v = new Ventas();
        jDesktopPane1.add(v);
        v.setVisible(true);
        v.setLocation(0, 0);
        v.setSize(1366, 768);
        v.setClosable(true);
        v.setIconifiable(true);
        v.setMaximizable(true);
        v.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        v.toFront();
        v.requestFocus();
        v.setResizable(false);
        v.setLocation(100, 0);
        v.show();
        

    }//GEN-LAST:event_VentasActionPerformed

    private void Consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta1ActionPerformed
        // TODO add your handling code here:
        c_Rentas rentas = new c_Rentas();
        inicializarFrame(rentas);
    }//GEN-LAST:event_Consulta1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
          // TODO add your handling code here:
          //presionar alt para navegar con los menus
            if (evt.getKeyCode() == KeyEvent.VK_ALT) {
                Inicio.setArmed(true);
                Inicio.setSelected(true);
                Inicio.requestFocus();
            }
    }//GEN-LAST:event_formKeyPressed

    private void ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprasActionPerformed
        // TODO add your handling code here:
        Compras v = new Compras();
        jDesktopPane1.add(v);
        v.setVisible(true);
        v.setLocation(0, 0);
        v.setSize(1366, 768);
        v.setClosable(true);
        v.setIconifiable(true);
        v.setMaximizable(true);
        v.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        v.toFront();
        v.requestFocus();
        v.setResizable(false);
        v.setLocation(100, 0);
        v.show();
    }//GEN-LAST:event_ComprasActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
        Clientes v = new Clientes();
        inicializarFrame(v);
    }//GEN-LAST:event_ClientesActionPerformed

    private void LibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrosActionPerformed
        // TODO add your handling code here:
        Libros v = new Libros();
        inicializarFrame(v);
    }//GEN-LAST:event_LibrosActionPerformed

    private void TarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetasActionPerformed
        // TODO add your handling code here:
        Tarjetas v = new Tarjetas();
        inicializarFrame(v);
    }//GEN-LAST:event_TarjetasActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        //Cierra todos los frames abiertos
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
        }
        
    }//GEN-LAST:event_LimpiarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        Proveedor proveedores = new Proveedor();
        inicializarFrame(proveedores);
    }   
    
     private void AutoresActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        Autores autores = new Autores();
        inicializarFrame(autores);
    } 
     
     private void inicializarFrame(JInternalFrame frame) {
        jDesktopPane1.add(frame);
        frame.setVisible(true);
        frame.setLocation(0, 0);
        frame.setClosable(true);
        frame.setIconifiable(true);
        frame.setMaximizable(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.toFront();
        frame.requestFocus();
        frame.setResizable(false);
        frame.setLocation(100, 100);
        frame.show();
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Abcs;
    private javax.swing.JMenuItem Autores;
    private javax.swing.JMenu Capturas;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenuItem Compras;
    private javax.swing.JMenuItem Consulta1;
    private javax.swing.JMenuItem Consulta2;
    private javax.swing.JMenuItem Consulta3;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenu Inicio;
    private javax.swing.JMenuItem Libros;
    private javax.swing.JMenu Limpiar;
    private javax.swing.JMenuItem Proveedores;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem Tarjetas;
    private javax.swing.JMenuItem Ventas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
